// Datapacks del servidor (carpeta datapacks/ del mundo, no van en la carpeta de mods).
// A diferencia de data.js, esta lista es curada a mano: los datapacks no traen un
// fabric.mod.json que se pueda extraer automáticamente, así que hay que actualizarla
// manualmente cada vez que se agregue o quite un datapack del mundo.
const DATAPACKS = [
  {
    "id": "dp_cauldron_concrete",
    "name": "Cauldron Concrete",
    "jar": "cauldron concrete v3.1.1 (MC 26.2).zip",
    "enabled": true,
    "version": "3.1.1",
    "authors": ["Vanilla Tweaks"],
    "category": "datapack",
    "category_label": "Datapack",
    "desc_es": "Convierte cemento en polvo a cemento sólido usando un caldero con agua, sin necesitar un bloque de agua normal.",
    "desc_original": "Turns concrete powder into concrete using a water cauldron.",
    "depends": [],
    "required_by": [],
    "recommends": [],
    "recommended_by": [],
    "modrinth_url": null,
    "icon_url": null
  },
  {
    "id": "dp_cauldron_mud",
    "name": "Cauldron Mud",
    "jar": "cauldron mud v1.0.10 (MC 26.2).zip",
    "enabled": true,
    "version": "1.0.10",
    "authors": ["Vanilla Tweaks"],
    "category": "datapack",
    "category_label": "Datapack",
    "desc_es": "Convierte tierra en lodo (mud) usando un caldero con agua, igual que con una fuente de agua normal.",
    "desc_original": "Turns dirt into mud using a water cauldron.",
    "depends": [],
    "required_by": [],
    "recommends": [],
    "recommended_by": [],
    "modrinth_url": null,
    "icon_url": null
  },
  {
    "id": "dp_double_shulker_shells",
    "name": "Double Shulker Shells",
    "jar": "double shulker shells v1.3.17 (MC 26.2).zip",
    "enabled": true,
    "version": "1.3.17",
    "authors": ["Vanilla Tweaks"],
    "category": "datapack",
    "category_label": "Datapack",
    "desc_es": "Los shulkers sueltan 2 caparazones (shulker shells) al morir en vez de 1, para no tener que ir tantas veces al End por cajas shulker.",
    "desc_original": "Shulkers drop 2 shulker shells instead of 1.",
    "depends": [],
    "required_by": [],
    "recommends": [],
    "recommended_by": [],
    "modrinth_url": null,
    "icon_url": null
  },
  {
    "id": "dp_ender_chest_always_drops",
    "name": "Ender Chest Always Drops",
    "jar": "ender chest always drops v1.0.9 (MC 26.2).zip",
    "enabled": true,
    "version": "1.0.9",
    "authors": ["Vanilla Tweaks"],
    "category": "datapack",
    "category_label": "Datapack",
    "desc_es": "El cofre de Ender siempre se puede recoger al minarlo, sin necesitar el encantamiento Seda Fantasma.",
    "desc_original": "Ender chests always drop themselves when mined, without needing Silk Touch.",
    "depends": [],
    "required_by": [],
    "recommends": [],
    "recommended_by": [],
    "modrinth_url": null,
    "icon_url": null
  },
  {
    "id": "dp_fast_leaf_decay",
    "name": "Fast Leaf Decay",
    "jar": "fast leaf decay v2.0.22 (MC 26.2).zip",
    "enabled": true,
    "version": "2.0.22",
    "authors": ["Vanilla Tweaks"],
    "category": "datapack",
    "category_label": "Datapack",
    "desc_es": "Las hojas de los árboles se caen mucho más rápido después de talar el tronco, en vez de tardar minutos en desaparecer.",
    "desc_original": "Leaves decay much faster after the tree trunk is chopped down.",
    "depends": [],
    "required_by": [],
    "recommends": [],
    "recommended_by": [],
    "modrinth_url": null,
    "icon_url": null
  },
  {
    "id": "dp_husks_drop_sand",
    "name": "Husks Drop Sand",
    "jar": "husks drop sand v1.0.10 (MC 26.2).zip",
    "enabled": true,
    "version": "1.0.10",
    "authors": ["Vanilla Tweaks"],
    "category": "datapack",
    "category_label": "Datapack",
    "desc_es": "Los husks (zombis del desierto) sueltan arena al morir.",
    "desc_original": "Husks drop sand on death.",
    "depends": [],
    "required_by": [],
    "recommends": [],
    "recommended_by": [],
    "modrinth_url": null,
    "icon_url": null
  },
  {
    "id": "dp_mini_blocks",
    "name": "Mini Blocks",
    "jar": "mini blocks v1.1.7 (MC 26.2).zip",
    "enabled": true,
    "version": "1.1.7",
    "authors": ["Vanilla Tweaks"],
    "category": "datapack",
    "category_label": "Datapack",
    "desc_es": "Te deja craftear versiones en miniatura de muchos bloques, para decorar con más detalle.",
    "desc_original": "Lets you craft miniature versions of many blocks for detailed builds.",
    "depends": [],
    "required_by": [],
    "recommends": [],
    "recommended_by": [],
    "modrinth_url": null,
    "icon_url": null
  },
  {
    "id": "dp_more_effective_tools",
    "name": "More Effective Tools",
    "jar": "more effective tools v1.0.11 (MC 26.2).zip",
    "enabled": true,
    "version": "1.0.11",
    "authors": ["Vanilla Tweaks"],
    "category": "datapack",
    "category_label": "Datapack",
    "desc_es": "Las herramientas de mayor nivel ya no se sienten más lentas al minar bloques pensados para herramientas de nivel más bajo.",
    "desc_original": "Higher-tier tools no longer mine slower on blocks meant for lower-tier tools.",
    "depends": [],
    "required_by": [],
    "recommends": [],
    "recommended_by": [],
    "modrinth_url": null,
    "icon_url": null
  },
  {
    "id": "dp_multiplayer_sleep",
    "name": "Multiplayer Sleep",
    "jar": "multiplayer sleep v2.6.17 (MC 26.2).zip",
    "enabled": true,
    "version": "2.6.17",
    "authors": ["Vanilla Tweaks"],
    "category": "datapack",
    "category_label": "Datapack",
    "desc_es": "Con varios jugadores, no hace falta que todos duerman para pasar la noche — basta con que un porcentaje configurado lo haga.",
    "desc_original": "Only a configurable percentage of players need to sleep to skip the night.",
    "depends": [],
    "required_by": [],
    "recommends": [],
    "recommended_by": [],
    "modrinth_url": null,
    "icon_url": null
  },
  {
    "id": "dp_painting_picker",
    "name": "Painting Picker",
    "jar": "painting picker v1.1.4 (MC 26.2).zip",
    "enabled": true,
    "version": "1.1.4",
    "authors": ["Vanilla Tweaks"],
    "category": "datapack",
    "category_label": "Datapack",
    "desc_es": "Al hacer clic derecho en un marco de cuadro vacío, puedes elegir qué cuadro quieres en vez de que salga uno al azar.",
    "desc_original": "Right-click an empty painting frame to choose which painting spawns.",
    "depends": [],
    "required_by": [],
    "recommends": [],
    "recommended_by": [],
    "modrinth_url": null,
    "icon_url": null
  },
  {
    "id": "dp_player_head_drops",
    "name": "Player Head Drops",
    "jar": "player head drops v1.1.17 (MC 26.2).zip",
    "enabled": true,
    "version": "1.1.17",
    "authors": ["Vanilla Tweaks"],
    "category": "datapack",
    "category_label": "Datapack",
    "desc_es": "Los jugadores dejan caer su propia cabeza al morir.",
    "desc_original": "Players drop their own head on death.",
    "depends": [],
    "required_by": [],
    "recommends": [],
    "recommended_by": [],
    "modrinth_url": null,
    "icon_url": null
  },
  {
    "id": "dp_storm_channeling",
    "name": "Storm Channeling",
    "jar": "storm channeling v1.0.9 (MC 26.2).zip",
    "enabled": true,
    "version": "1.0.9",
    "authors": ["Vanilla Tweaks"],
    "category": "datapack",
    "category_label": "Datapack",
    "desc_es": "El encantamiento Canalización del tridente funciona con cualquier lluvia, no solo durante una tormenta eléctrica.",
    "desc_original": "The Channeling trident enchantment works in any rain, not just thunderstorms.",
    "depends": [],
    "required_by": [],
    "recommends": [],
    "recommended_by": [],
    "modrinth_url": null,
    "icon_url": null
  },
  {
    "id": "dp_unlock_all_recipes",
    "name": "Unlock All Recipes",
    "jar": "unlock all recipes v2.0.18 (MC 26.2).zip",
    "enabled": true,
    "version": "2.0.18",
    "authors": ["Vanilla Tweaks"],
    "category": "datapack",
    "category_label": "Datapack",
    "desc_es": "Desbloquea todas las recetas del juego desde el inicio en el libro de recetas, sin tener que ir descubriéndolas de a poco.",
    "desc_original": "Unlocks all recipes in the recipe book from the start.",
    "depends": [],
    "required_by": [],
    "recommends": [],
    "recommended_by": [],
    "modrinth_url": null,
    "icon_url": null
  },
  {
    "id": "dp_villager_death_messages",
    "name": "Villager Death Messages",
    "jar": "villager death messages v1.2.19 (MC 26.2).zip",
    "enabled": true,
    "version": "1.2.19",
    "authors": ["Vanilla Tweaks"],
    "category": "datapack",
    "category_label": "Datapack",
    "desc_es": "Muestra un mensaje en el chat cuando muere un aldeano, con la causa de su muerte.",
    "desc_original": "Shows a chat message with the cause of death when a villager dies.",
    "depends": [],
    "required_by": [],
    "recommends": [],
    "recommended_by": [],
    "modrinth_url": null,
    "icon_url": null
  },
  {
    "id": "dp_villager_workstation_highlights",
    "name": "Villager Workstation Highlights",
    "jar": "villager workstation highlights v1.1.17 (MC 26.2).zip",
    "enabled": true,
    "version": "1.1.17",
    "authors": ["Vanilla Tweaks"],
    "category": "datapack",
    "category_label": "Datapack",
    "desc_es": "Al interactuar con un aldeano, resalta con un efecto visual el puesto de trabajo al que está ligado (yunque, atril, etc.).",
    "desc_original": "Highlights a villager's linked workstation block when you interact with them.",
    "depends": [],
    "required_by": [],
    "recommends": [],
    "recommended_by": [],
    "modrinth_url": null,
    "icon_url": null
  }
];
